AllCops:
  Include:
  - Rakefile
  - config.ru
  Exclude:
  - db/schema.rb
  - script/**/*
  - bin/*

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
  - config/initializers/devise.rb

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  EnforcedStyle: nested

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

# FIXME:
# Configuration parameters: Include.
Rails/HasAndBelongsToMany:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/MethodLength:
  Max: 70

Style/TrivialAccessors:
  ExactNameMatch: true

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  AlignWith: variable
